#!/usr/bin/env perl
use strict;
use warnings;
# use diagnostics;

$ENV{LANG} = 'C';

sub get_volume {
    if (substr(`pactl get-sink-mute \@DEFAULT_SINK\@`, -3, 3) eq "yes"){
        return -1
    }

    # get volume
    my $volume = `pactl get-sink-volume \@DEFAULT_SINK\@`;
    $volume =~ /.+?(\d+)%/;
    return $1;
}

sub wrap_str {
    return "<span size='x-small'>" . $_[0] . "</span>\n";
}

sub set_sink {
    system("pactl", "set-sink-" . $_[0], '@DEFAULT_SINK@', $_[1]);
}

sub block_button_parse {
    if ($_[0] == 1) {
        set_sink("mute", "toggle");
    } elsif ($_[0] == 4) {
        set_sink("volume", "+5%");
    } elsif ($_[0] == 5) {
        set_sink("volume", "-5%");
    }
}

if ($ENV{BLOCK_BUTTON} ~~ [ 1, 4, 5 ]){
    block_button_parse($ENV{BLOCK_BUTTON})
} elsif ($ARGV[0]){
    set_sink($ARGV[1], $ARGV[2])
}

my $volume = get_volume();

if ($ENV{BLOCK_BUTTON} or $ARGV[0]) {
    if ($volume == -1) {
        system("dunstify", "--replace=999", "Volume", "muted");
    } else {
        system("dunstify", "--replace=999", "--hints=int:value:" . $volume, "Volume");
    }
}

if ($volume < 0) {
    print(wrap_str(""));
} elsif ($volume < 100) {
    print(wrap_str($volume));
} elsif ($volume = 100) {
    print("\n");
} else {
    print("<span foreground=\"#" . $ENV{__BASE08} . "\">" . wrap_str($volume));
}

if ($ARGV[0]) {
    system("pkill", "-RTMIN+" . $ARGV[0], "i3blocks")
}
