#!/bin/bash

function bold {
    echo -e "\x1b[1;32m::\x1b[0m \x1b[1m${@}\x1b[22m"
}

function prompt {
    bold "$@"
    read -sn 1 -p 'Press any key to continue.'
    echo
}

blkdev=$@

if [[ -z "$blkdev" ]]; then
    bold "No cryptdevice specified."
    exit 1
elif [[ ! -e "/dev/mapper/$blkdev" ]]; then
    bold "No device at /dev/mapper/$blkdev"
    exit 1
elif findmnt -n /mnt; then
    bold "Mountpoint /mnt occupied."
    exit 1
fi

bold "Mounting /dev/mapper/$blkdev at /mnt..."
mount /dev/mapper/$blkdev /mnt

prompt "Creating top-level subvolumes..."
for sub in @ @home @snp; do
    btrfs -v subvolume create /mnt/$sub
done

prompt "Unmounting /dev/mapper/$blkdev..."
umount -v -R /mnt

prompt "Mounting top-level subvolumes..."
mount -v -o compress=zstd,subvol=@ /dev/mapper/$blkdev /mnt

for sub in home snp; do
    mkdir -pv /mnt/$sub
    mount -v -o compress=zstd,subvol=@$sub /dev/mapper/$blkdev /mnt/$sub
done

prompt "Creating /var sub-directory subvolumes..."
mkdir -pv /mnt/var
for sub in var cache log; do
    btrfs -v subvolume create /mnt/var/$sub
done

prompt "Creating swap subvolume and file..."
btrfs -v subvolume create /mnt/swap
cd /mnt/swap
truncate -s 0 ./swapfile
chattr -V +C ./swapfile
btrfs -v property set ./swapfile compression none
read -p "Size of swap file in MB: " swapsize
dd if=/dev/zero of=./swapfile bs=1M count=$swapsize status=progress
chmod -c 600 ./swapfile
mkswap --verbose ./swapfile

prompt "Swapping on..."
swapon -v ./swapfile

cd /
bold "Done!"
